name: Pull Request

on: [pul_request]

jobs:
  isntall:
    name: Install Packages
    runs-on: ubuntu-latest
      - name: Checkout
        uses: actions/checkout@v3
      - name: cache node_modules
        uses: actions/cache@v2
        with: 
          path: node_modules
          key: ${{ runner.os}}-{{ hashFiles('**/yarn.lock')}}
      - name: Install dependencies
        run: yarn install  
  unusedexports:
    name: check unused exports
    runs-on: ubuntu-latest
    needs: install
      - name: Checkout
        uses: actions/checkout@v3
      - name: restore node_modules
        uses: actions/cache@v2
        with: 
          path: node_modules
          key: ${{ runner.os}}-{{ hashFiles('**/yarn.lock')}}

      - name: Run ts-prune
        run: yarn ts-prune --error  